weights: runs/train/exp4/weights/best.pt
cfg: ''
data: Edited_version-7/data.yaml
hyp:
  lr0: 0.00816
  lrf: 0.01
  momentum: 0.88214
  weight_decay: 0.0005
  warmup_epochs: 4.2752
  warmup_momentum: 0.82397
  warmup_bias_lr: 0.08129
  box: 0.05158
  cls: 0.42368
  cls_pw: 1.2722
  obj: 0.92714
  obj_pw: 0.92939
  iou_t: 0.2
  anchor_t: 3.6957
  fl_gamma: 0.0
  hsv_h: 0.01642
  hsv_s: 0.76065
  hsv_v: 0.29355
  degrees: 0.0
  translate: 0.08775
  scale: 0.44663
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
  anchors: 3.1079
epochs: 6
batch_size: 80
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 8
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp3
